### PR TITLE
Feature/invalid required fields red border

### PR DESCRIPTION
**Pull request by ThomasDThales**
Validity checks on SupportingAssets, AttackPaths and BusinessAssets updated
Error styles added to the required files
Update of styles
Displaying "Select... " as default for select inputs

### CODE REVIEW

**Comment by Alvin-JohnPagente** [comment]
We can probably make the behavior consistent where the red border is applied.

For example:
Here the dropdown is highlighted as red but the dropdown header is not
image

Here the header is red but the field does not have a red border
image

**Comment by Alvin-JohnPagente** [comment]
The vulnerability name should be mandatory... but it does not have a red border

image

**Comment by Alvin-JohnPagente** [comment]
In the Business Assets tab, name should be mandatory
image

In the supporting asset, the business asset without a name should be red
image

**Comment by ThomasDThales** [comment]
Same for Supporting Assets' name.

**Comment by ThomasDThales** [comment]
> We can probably make the behavior consistent where the red border is applied.
> 
> For example: Here the dropdown is highlighted as red but the dropdown header is not image
> 
> Here the header is red but the field does not have a red border image

The consistence is respected regarding the documentation

**Comment by ThomasDThales** [comment]
Updated behavior:
- Inputs display errors either with bigger border width and red border color or red color on the related label (Both display can be used,  example for 'VulnerabilityName')
image
- These errors are triggered by: unfilled required fields, fields filled with unknown references (example : attack paths containing references of deleted Vulnerabilities) and references of nonvalid objects
- Each error is also mentioned in the Error popup displayed when saving
- The type of the displayed error make the input have a specific behaviors:
  -  The "unfilled required fields" and "fields filled with unknown references" errors set the value of the input as default (empty for text inputs, "Select" for select inputs)
  -  The "references of nonvalid objects" error has no impact on the value of the input

**Comment by ThomasDThales** [comment]
> The vulnerability name should be mandatory... but it does not have a red border
> 
> image

Fixed

**Comment by ThomasDThales** [comment]
> In the Business Assets tab, name should be mandatory image
> 
> In the supporting asset, the business asset without a name should be red image

For the display of business asset without a name in a supporting asset : Fixed
For the display that a Supporting name is required, will be done in an other feature. The goal is to have a consistent display of this error for every item (SA, BA, Vulnerability, Risk)

**Review by Alvin-JohnPagente — COMMENTED** [review]
**Supporting asset**: confirmed
- In the Relationship Matrix, changed select Business asset in supporting asset to red border when not set. When the value is "Select", a red border is visible.
- In the Relationship Matrix, changed select Business asset in supporting asset to red border when not set. The  business asset box is now red
-  In the Relationship Matrix, adding name check for valid business asset in supporting assets. Now the box is red if the business asset has an empty name
- 
**Vulnerabilities**: confirmed
- Add title colors for the Description and Support Assets inputs in Vulnerability Panel when invalid
- adding display of vulnerability name error in vulnerability panel. Now if the vulnerability name is empty the text input title is red

**Risks**: Confirmed
- Change the condition of input values (Business Asset & Supporting Asset) to be set as valid items only or "Select..." input. Now invalid Business Assets and Supporting Assets are visible
- modify the validate function and add the attackpaths condition to fix…
… the issue where risks where not red when vulnerabilities / business assets / supporting assets are deleted. Now the risk in the table is red when the business asset, supporting asset, and vulnerability is deleted
- fixed the issue where risk invalidation from deleted vulnerability was not shown while saving. Now the error is shown in the Save error dialog

**Review by Alvin-JohnPagente — APPROVED** [review]
Wheww! Approved!

**Pull request merged**
