### PR TITLE
deleted displaying Decision Comment when adding a risk

### PR DESCRIPTION
**Pull request by ThomasDThales**
A function was executed at the wrong time so implied an error and was in fact useless

### CODE REVIEW

**Comment by Alvin-JohnPagente** [comment]
To reproduce the issue:
- Launch sratool
- Go to Risks tab. The tab will have one risk by default. Scroll to the Risk Mitigation...
image
- Now add a new Risk. The active risk is #1.
image
- Scroll to the Risk Mitigation, notice that the mitigation decision is shown even when the decision = Not defined
image

**Comment by Alvin-JohnPagente** [comment]
@ThomasDThales This pull requests fixes 2 issues. Can you update the pull request title to describe the pull request more accurately

**Comment by ThomasDThales** [comment]
> @ThomasDThales This pull requests fixes 2 issues. Can you update the pull request title to describe the pull request more accurately

Done

**Review by Alvin-JohnPagente — APPROVED** [review]
Confirmed that issue is fixed

**Pull request merged**
